epidemiology:
  enabled: true
  source: "KAGGLE"
  dataset_id: "emmanuelniyioriolowo/ncdc-lassa-fever-timeseries-20202025"

  files:
    full: "lassa_fever_timeseries_full.csv"
    minimal: "lassa_fever_timeseries_minimal.csv"

  default: "full"

  raw_directory: "data/raw/epidemiology"

weather:
  enabled: true
  source: "NASA_POWER"
  filename: "weather.csv"
  raw_directory: "data/raw/weather"

population:
  enabled: true
  source: "GRID3"
  filename: "population.csv"
  raw_directory: "data/raw/population"

geography:
  enabled: true
  source: "GRID3"
  filename: "geography.geojson"
  raw_directory: "data/raw/geography"
